---
- name: Create temp directory for doing work in
  command: mktemp -d /tmp/logging-ocp-XXXXXX
  register: mktemp
  changed_when: False
  check_mode: no

- set_fact:
    tmp_dir: "{{ mktemp.stdout }}"