---

- name: "Elasticsearch: template ES Config"
  template:
    src: "{{ item }}.j2"
    dest: "{{ tmp_dir }}/{{ item }}"
  loop:
    # - "elastic-catalogsourceconfig.yml"
    - "elastic-operatorgroup.yml"
    - "elastic-role.yml"
    - "elastic-rolebinding.yml"

- name: "Elasticsearch: Apply OperatorGroup"
  oc_obj:
    name: openshift-operators-redhat
    kubeconfig: "{{ kube_config_path }}"
    state: present
    namespace: "{{ elastic_namespace }}"
    kind: OperatorGroup
    files:
    - "{{ tmp_dir }}/elastic-operatorgroup.yml"

# - name: "Elasticsearch: Apply CatalogSourceConfig"
#   oc_obj:
#     name: elasticsearch
#     kubeconfig: "{{ kube_config_path }}"
#     state: present
#     namespace: openshift-marketplace
#     kind: CatalogSourceConfig
#     files:
#     - "{{ tmp_dir }}/elastic-catalogsourceconfig.yml"

- name: "Elasticsearch: Apply Role"
  oc_obj:
    name: prometheus-k8s
    kubeconfig: "{{ kube_config_path }}"
    state: present
    namespace: "{{ elastic_namespace }}"
    kind: Role
    files:
    - "{{ tmp_dir }}/elastic-role.yml"

- name: "Elasticsearch: Apply RoleBinding"
  oc_obj:
    name: prometheus-k8s
    kubeconfig: "{{ kube_config_path }}"
    state: present
    namespace: "{{ elastic_namespace }}"
    kind: RoleBinding
    files:
    - "{{ tmp_dir }}/elastic-rolebinding.yml"

- name: "Elasticsearch: Get packagemanifest"
  oc_obj:
    name: elasticsearch-operator
    kubeconfig: "{{ kube_config_path }}"
    state: list
    namespace: openshift-marketplace
    kind: PackageManifest
  register: pckmnfst

- name: Debug packagemanifest
  debug:
    var: pckmnfst

- name: "Debug packagemanifest channel"
  debug:
    msg: "test: {{ pckmnfst.module_results.results[0].status.channels[0].name }}"

- set_fact:
    elastic_channel: "{{ pckmnfst.module_results.results[0].status.channels[0].name }}"

- name: "Elasticsearch: template ES Subscription"
  template:
    src: "{{ item }}.j2"
    dest: "{{ tmp_dir }}/{{ item }}"
  loop:
    - "elastic-subscription.yml"

- name: "Elasticsearch: Apply Subscription"
  oc_obj:
    name: elasticsearch-operator
    kubeconfig: "{{ kube_config_path }}"
    state: present
    namespace: "{{ elastic_namespace }}"
    kind: Subscription
    files:
    - "{{ tmp_dir }}/elastic-subscription.yml"