---

- name: Deploy Coolstore Microservices Demo - CI/CD with JBoss EAP
  hosts: all
  gather_facts: false
  run_once: true

  tasks:
    - include_role:
        name: openshift_common_facts
      tags:
        - cicd


    - import_role:
        name: openshift_sonatype_nexus
      vars:
        project_name: "{{ project_cicd }}"
      when: >
        maven_mirror_url is not defined or
        maven_mirror_url is none or
        maven_mirror_url|trim() == ""
      tags: cicd